version: '3.8'

services:
  ui:
    image:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - target: 80      
        published: 80
        protocol: tcp
        mode: ingress 
   
  api:
    image:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - target: 80      
        published: 80
        protocol: tcp
        mode: ingress 


    
  
    
      